# Jekyll Configuration for Prosper XO Website
# This config only processes the blog - rest of site remains static

# Site settings
title: "Prosper XO"
description: "Prosper XO - Music and Community"
baseurl: "" # Leave empty for root domain
url: "https://prosperxo.com" # Replace with your actual domain

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

# Use Jekyll's default _posts directory
# No collections needed - Jekyll automatically processes _posts

# Exclude directories from Jekyll processing
# This ensures your static HTML/CSS/JS files are not processed
exclude:
  - node_modules
  - scripts
  - cms
  - assets/graphics
  - assets/placeholders
  - assets/posters
  - assets/text
  - assets/thumbnail
  - assets/vcards
  - assets/video
  - assets/definitions
  - assets/letters
  - assets/header_footer_code_templates
  - assets/data
  - staging-wip
  - README-BUILD.md
  - package.json
  - package-lock.json
  - sitemap.xml
  - robots.txt
  - CNAME
  - 404.html
  - beta-signup
  - ethos
  - events
  - faq
  - get-involved
  - id
  - letter
  - newsletter-signup
  - next-event
  - qr
  - surveys
  - team
  - welcome
  - why-prosper
  - xo-insider

# Include only what we need for the blog
include:
  - assets/blog/uploads
  - assets/blog/posts

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Prosper XO"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Plugins (minimal for GitHub Pages compatibility)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Kramdown settings
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
