# Jekyll Configuration for Prosper XO Website
# This config only processes the blog - rest of site remains static

# Site settings
title: "Prosper XO"
description: "Prosper XO - Music and Community"
baseurl: "" # Leave empty for root domain
url: "https://prosperxo.com" # Replace with your actual domain

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

# Use Jekyll's default _posts directory
# No collections needed - Jekyll automatically processes _posts

# Keep static files in _site (they're copied there before Jekyll runs)
keep_files:
  - index.html
  - welcome
  - team
  - ethos
  - events
  - faq
  - get-involved
  - id
  - letter
  - newsletter-signup
  - next-event
  - qr
  - surveys
  - why-prosper
  - xo-insider
  - beta-signup
  - content
  - assets
  - cms
  - 404.html
  - CNAME
  - robots.txt
  - sitemap.xml

# Exclude files from Jekyll processing
exclude:
  - node_modules
  - vendor
  - scripts
  - staging-wip
  - README-BUILD.md
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - docker-jekyll.sh
  - JEKYLL-INTEGRATION.md
  - .github

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Prosper XO"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Plugins (minimal for GitHub Pages compatibility)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Kramdown settings
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
