[build]
  publish = "_site"
  command = "bundle install && npm install && npm run build"

# Redirect Netlify subdomain to custom domain
# Temporarily disabled until custom domain is fully ready
# [[redirects]]
#   from = "https://prosper-xo-blog.netlify.app/*"
#   to = "https://prosperxo.com/:splat"
#   status = 301
#   force = true

# Headers for better caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "public, max-age=300"
