[build]
  publish = "."
  command = "npm install && npm run build"

# Explicitly serve config.yml as static file
[[headers]]
  for = "/config.yml"
  [headers.values]
    Content-Type = "text/yaml"

# No redirects needed - CMS is at root directory
