[build]
  publish = "."
  command = "echo 'No build command needed for CMS'"

# Explicitly serve config.yml as static file
[[headers]]
  for = "/config.yml"
  [headers.values]
    Content-Type = "text/yaml"

# Redirect admin routes to CMS
[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200
